### ISSUE TITLE
vim stuck while closing

### ISSUE THREAD

**Issue by guoxiao** [jeaye/color_coded#135]
My vim often stop responding while closing if I enable color_coded, and I have to `kill -9` to stop it.

I tried to attach gdb to vim and print the backtrace, which was like this:

```
(gdb) bt
#0  0x00007f6d7c6ae6bd in pthread_join () from /lib64/libpthread.so.0
#1  0x00007f6d6ea6a217 in std::thread::join() () from /lib64/libLLVM-3.8.so
#2  0x00007f6d74250ee8 in int color_coded::detail::safe_func<int (*)(lua_State*), &color_coded::exit>::call<lua_State*>(lua_State*) () from /home/xxxx/.vim/bundle/color_coded/color_coded.so
#3  0x00007f6d7449611e in luaD_precall () from /lib64/liblua-5.3.so
#4  0x00007f6d744abcc5 in luaV_execute () from /lib64/liblua-5.3.so
#5  0x00007f6d7449650f in luaD_call () from /lib64/liblua-5.3.so
#6  0x00007f6d74496561 in luaD_callnoyield () from /lib64/liblua-5.3.so
#7  0x00007f6d74495932 in luaD_rawrunprotected () from /lib64/liblua-5.3.so
#8  0x00007f6d744967ed in luaD_pcall () from /lib64/liblua-5.3.so
#9  0x00007f6d7448d141 in lua_pcallk () from /lib64/liblua-5.3.so
#10 0x000056473c7bb95f in ex_lua ()
#11 0x000056473c69861a in do_cmdline ()
#12 0x000056473c66bc9b in call_func ()
#13 0x000056473c670742 in get_func_tv ()
#14 0x000056473c67878f in ex_call ()
#15 0x000056473c69861a in do_cmdline ()
#16 0x000056473c6aeccf in apply_autocmds_group ()
#17 0x000056473c6af8c4 in apply_autocmds ()
#18 0x000056473c7e80b0 in getout ()
#19 0x000056473c691f0b in ex_exit ()
#20 0x000056473c69861a in do_cmdline ()
#21 0x000056473c7059d5 in nv_colon ()
#22 0x000056473c70e81b in normal_cmd ()
#23 0x000056473c7e8775 in main_loop ()
#24 0x000056473c63205f in main ()
```

**Comment by jeaye** [comment]
That's a very interesting backtrace! Thanks for the report.
